### ISSUE TITLE
Segmentation error when execuiting flexprop.bin version 5.9.8

### ISSUE THREAD

**Issue by DataGeorge** [totalspectrum/flexprop#54] opened 2022-02-04 01:23 UTC
This is in Linuxmint 20.3 terminal.  I believe I followed all the install instructions correctly.  I notice warnings in the make install process that referred to ignoring the return value from 'getcwd' and a 'write' function.

This execution was after cloning from github and running the make install.

This same error occurred when I installed flexprop using gdebi on the  .deb vesion download.

 ./flexprop.bin
Error in startup script: child killed: segmentation violation
    while executing
"exec -ignorestderr $ROOTDIR/bin/proploader$EXE -W"
    (procedure "rescanPorts" line 21)
    invoked from within
"rescanPorts"
    (file "/home/georgem/Programs/flexprop/src/gui.tcl" line 2345)
    invoked from within
"source $ROOTDIR/src/gui.tcl"
    (file "/home/georgem/Programs/flexprop/src/flexprop.tcl" line 30)

**Comment by DataGeorge** [comment] 2022-02-04 16:34
I apologize.  I am traveling and was experimenting with the latest code while listening to the P2 forum yesterday.  I did not tell you I do not have a P2  plugged in.  Sorry.  
Maybe I am executing the wrong thing.  I used 'flexprop.bin' as that is the only executable in the flexprop folder.  Note: '_flexprop.bin_' not '_flexprop_'.  I tried running "proploader -W" directly but got a segmentation error.  If this occurs only  because I don't have the P2 plugged in, then it is a minor error.

**Comment by totalspectrum** [comment] 2022-02-05 02:23
There are two issues:

(1) Something seems to have gone wrong with your install, as the executable name after the default install should be $HOME/flexprop/flexprop. There does seem to be a problem building on Linux Mint which was reported on the forums, and I've checked in a fix for that.

(2) The segmentation violation from proploader is utterly mystifying. What kind of system are you running on? Is it an x86? If so, 32 bit or 64 bit? Are you familiar with gdb (or any other debugger)? If so, if you could run "gdb --args proploader -W" and then get a stack trace when the segmentation fault happens that would be very helpful.

**Comment by totalspectrum** [comment] 2022-09-07 10:47
Closing as no further info provided and unable to reproduce.

**Closed by totalspectrum** 2022-09-07 10:47 UTC
