### ISSUE TITLE
Wrap arguments to external programs in quotes 

### ISSUE THREAD

**Issue by bartgrantham** [totalspectrum/flexprop#19] opened 2020-06-02 09:41 UTC
Compile & Run bombed for a file in a directory with a space with the error: **"too many files specified on command line"**

Looking at the output the problem is obvious:

> /Users/bart/Code/Prop2/Others/flexgui/bin/loadp2.mac -b230400 /Users/bart/Code/Prop2/Others/propeller/resources/FPGA Examples/NTSC_256_x_192.binary -9/Users/bart/Code/Prop2/Others/propeller/resources/FPGA Examples -k; osascript -e 'tell application "Wish" to activate'; exit 0

The directory is "FPGA Examples", so that looks like two files to `load2p`.  I think just wrapping each arg for each external program invocation with single-quotes would solve most cases (files/directories that themselves contain single-quotes being the corner case).

**Comment by totalspectrum** [comment] 2020-06-03 13:03
Actually the problem is Mac specific and comes from the Mac program used to launch the applications in a terminal, namely bin/mac_terminal.sh. FlexGUI is passing the arguments quoted to that script, but when it invokes osascript the quotes are lost.

The mac_terminal.sh script looks like:
#!/bin/sh                                                                       
osascript <<EOF                                                                 
tell application "Terminal"                                                     
  do script "$*; osascript -e 'tell application \"Wish\" to activate'; exit 0"  
  activate                                                                      
end tell                                                                        
EOF                                                                             

I tried changing $* to $@ but it didn't help. I'm not familiar enough with osascript to figure out a way to add the quotes back in. Do you know of a fix for this?

**Comment by bartgrantham** [comment] 2020-06-04 01:17
Hm..  I'll take a look tonight or tomorrow.  I don't know osascript either, but maybe I can figure out a trick and pass it back to you.

**Closed** 2021-01-09 02:17 UTC
